### ISSUE TITLE
Clarify the command to run Bender

### ISSUE THREAD

**Issue by vlisovsk** [lhcb/starterkit-lessons#45]
In the [Exploring the DST lesson](https://lhcb.github.io/starterkit-lessons/first-analysis-steps/interactive-dst.html), it is mentioned the function
>   seekStripDecision (which replaces our advance)

It is worth mentioning, that to reproduce the same behavior as `advance(line)`, the following syntax should be used: `seekStripDecision('Stripping'+line+'Decision')`.

**Comment by goi42** [comment]
resolved: pull request #46

**Comment by eduardo-rodrigues** [comment]
I was looking at open issues and to me this one can be closed. What do you think @alexpearce or @chrisburr or @vlisovsk?

**Comment by alexpearce** [comment]
The PR was closed so in principle the problem still exists. I don't have a feeling for the priority; we could close it and address it later if it comes up again.

**Comment by eduardo-rodrigues** [comment]
Oops, you're right. I too quickly read as merged/done! Then leave it open :-).
